POST http://localhost:3000/createUser/create HTTP/1.1
 Content-Type: application/json

 {
     "nome": "Wesley duarte",
     "senha" :"1234546547",
     "email" : "@wesleyduarte.com@@"
 }

###
GET http://localhost:3000/usuarios 

###
PUT http://localhost:3000/usuarios/update/5faa9f5856f39424e8b4de69 HTTP/1.1
Content-Type: application/json
{
     "nome": "Mack",
     "senha" :"7375736",
     "email" : "@mack.com"
 }






